trigger:
- main

pool:
  name: Default  # Tu agente local, por ejemplo "MacBook-Pro-de-Santos"

stages:
# =====================
# 🧱 BUILD & TEST
# =====================
- stage: BuildAndTest
  displayName: "🏗️ Build & Test"
  jobs:
  - job: Build
    steps:
    - checkout: self

    # === BACKEND ===
    - script: |
        echo "🧩 Compilando API .NET..."
        cd Marketplace.Api
        dotnet restore
        dotnet build --no-restore
        dotnet test --no-build --logger "trx;LogFileName=test_results.trx"
      displayName: "Build & Test Backend"

    # === FRONTEND ===
    - script: |
        echo "🧩 Instalando Node.js 18..."
        brew install node@18 || true
        export PATH="/opt/homebrew/opt/node@18/bin:$PATH"
        node -v
        npm -v
      displayName: "Instalar Node.js 18"

    - script: |
        echo "🧱 Construyendo Frontend..."
        cd marketplace.frontend
        npm install
        npm run build
        mkdir -p ../marketplace-drop/frontend
        cp -r dist/* ../marketplace-drop/frontend/
      displayName: "Build Frontend (solo archivos finales)"

    # === PUBLICAR ARTIFACT ===
    - task: PublishBuildArtifacts@1
      displayName: "📦 Publicar Artifact Optimizado"
      inputs:
        PathtoPublish: 'marketplace-drop'
        ArtifactName: 'marketplace'
        publishLocation: 'Container'
      condition: succeeded()

# =====================
# 🚀 DEPLOY QA
# =====================
- stage: QA_Deploy
  displayName: "Deploy QA"
  dependsOn: BuildAndTest
  condition: succeeded()
  jobs:
  - job: QA
    steps:
    - script: |
        echo "Desplegando a entorno QA..."
        echo "Simulación de despliegue QA completada ✅"
      displayName: "Deploy QA Job"

# =====================
# 🚀 DEPLOY PRODUCCIÓN
# =====================
- stage: PROD_Deploy
  displayName: "Deploy Producción"
  dependsOn: QA_Deploy
  condition: succeeded()
  jobs:
  - job: PROD
    steps:
    - script: |
        echo "Desplegando a Producción..."
        echo "Simulación de despliegue Producción completada ✅"
      displayName: "Deploy PROD Job"
